# Generated by Django 5.2.15 on 2026-07-03 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Выберите одну или несколько ролей пользователя в процессе согласования. Именно роли определяют, какие этапы и проверки будут доступны пользователю.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='org_unit',
            field=models.ForeignKey(blank=True, help_text="Начните вводить название подразделения и выберите вариант из списка. Кнопка '+' создает новое подразделение.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='directory.orgunit', verbose_name='Подразделение'),
        ),
    ]
