# Generated by Django 5.1.8 on 2026-07-06 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_groups_alter_user_org_unit'),
        ('directory', '0002_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='org_unit',
            field=models.ForeignKey(blank=True, help_text="Начните вводить название группы и выберите вариант из списка. Кнопка '+' создает новую группу.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='directory.orgunit', verbose_name='Группа'),
        ),
    ]
