# Generated by Django 5.2.15 on 2026-07-08 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sync_non_root_users'),
        ('directory', '0005_position_alter_articletype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_directory_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='ID сотрудника во внешнем справочнике'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='directory.position', verbose_name='Должность'),
        ),
    ]
