# Generated by Django 5.2.15 on 2026-07-09 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_external_directory_id_user_position'),
        ('directory', '0005_position_alter_articletype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chair_org_unit',
            field=models.ForeignKey(blank=True, help_text='Кафедра из кадрового справочника. Не используется как рабочая группа маршрута.', limit_choices_to={'name__startswith': 'Кафедра'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chair_users', to='directory.orgunit', verbose_name='Кафедра'),
        ),
    ]
