# Generated by Codex on 2026-07-09

from django.db import migrations


CHAIR_HEAD_ROLE_NAME = "Заведующий кафедрой"
CHAIR_HEAD_POSITION_NAME = "Заведующий кафедрой"


def create_chair_head_role(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    OrgUnit = apps.get_model("directory", "OrgUnit")
    User = apps.get_model("accounts", "User")

    chair_head_role, _ = Group.objects.get_or_create(name=CHAIR_HEAD_ROLE_NAME)

    for chair_org_unit in OrgUnit.objects.filter(name__startswith="Кафедра"):
        chair_org_unit.available_roles.add(chair_head_role)

    valid_user_ids = set(
        User.objects.filter(
            position__name=CHAIR_HEAD_POSITION_NAME,
            chair_org_unit__isnull=False,
        ).values_list("id", flat=True)
    )
    through_model = User.groups.through
    existing_user_ids = set(
        through_model.objects.filter(group_id=chair_head_role.id).values_list("user_id", flat=True)
    )

    missing_links = [
        through_model(user_id=user_id, group_id=chair_head_role.id)
        for user_id in valid_user_ids
        if user_id not in existing_user_ids
    ]
    if missing_links:
        through_model.objects.bulk_create(missing_links, ignore_conflicts=True)

    stale_user_ids = existing_user_ids - valid_user_ids
    if stale_user_ids:
        through_model.objects.filter(group_id=chair_head_role.id, user_id__in=stale_user_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_chair_org_unit"),
        ("directory", "0004_populate_available_roles"),
    ]

    operations = [
        migrations.RunPython(create_chair_head_role, migrations.RunPython.noop),
    ]
