# Generated by Django 5.2.15 on 2026-07-03 10:44

import apps.submissions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('abstract', models.TextField(blank=True, verbose_name='Аннотация')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлена'), ('auto_checking', 'Автопроверка'), ('in_review', 'На согласовании'), ('revision_requested', 'На доработке'), ('approved', 'Согласована'), ('rejected', 'Отклонена')], default='draft', max_length=32, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлена')),
                ('article_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='directory.articletype', verbose_name='Тип статьи')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='directory.journal', verbose_name='Журнал')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SubmissionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Номер версии')),
                ('file', models.FileField(upload_to=apps.submissions.models.submission_version_upload_to, verbose_name='Файл')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='submissions.submission', verbose_name='Заявка')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_submission_versions', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Версия заявки',
                'verbose_name_plural': 'Версии заявки',
                'ordering': ('submission_id', 'version_number'),
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='submissions.submissionversion', verbose_name='Текущая версия'),
        ),
        migrations.AddConstraint(
            model_name='submissionversion',
            constraint=models.UniqueConstraint(fields=('submission', 'version_number'), name='unique_submission_version_number'),
        ),
    ]
