# Generated by Django 5.2.15 on 2026-07-05 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_direction'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='direction',
            field=models.ForeignKey(blank=True, help_text='Направление выбирается пользователем при отправке статьи на согласование.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='directory.direction', verbose_name='Направление согласования'),
        ),
    ]
