# Generated by Django 5.2.15 on 2026-07-09 08:55

import apps.submissions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_position_alter_articletype_options_and_more'),
        ('submissions', '0005_submission_appeal'),
        ('workflow', '0009_alter_routetemplate_options_alter_routetemplate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='directory.articletype', verbose_name='Тип материала'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='direction',
            field=models.ForeignKey(blank=True, help_text='Область экспертизы выбирается пользователем при отправке материала на согласование.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='directory.direction', verbose_name='Область экспертизы'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='route_template',
            field=models.ForeignKey(blank=True, help_text='Базовый маршрут обычно определяется типом материала автоматически. Область экспертизы влияет на состав согласующих внутри его шагов.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='workflow.routetemplate', verbose_name='Шаблон маршрута'),
        ),
        migrations.AlterField(
            model_name='submissionappeal',
            name='attachment',
            field=models.FileField(blank=True, upload_to=apps.submissions.models.submission_appeal_upload_to, verbose_name='Файл апелляции'),
        ),
    ]
