# Generated by Codex on 2026-07-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_submission_authors(apps, schema_editor):
    Submission = apps.get_model("submissions", "Submission")
    through_model = Submission.authors.through

    existing_links = set(
        through_model.objects.values_list("submission_id", "user_id")
    )
    links_to_create = []
    for submission_id, author_id in Submission.objects.exclude(author_id__isnull=True).values_list("id", "author_id"):
        key = (submission_id, author_id)
        if key in existing_links:
            continue
        links_to_create.append(
            through_model(submission_id=submission_id, user_id=author_id)
        )

    if links_to_create:
        through_model.objects.bulk_create(links_to_create, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0006_alter_submission_article_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="author",
            field=models.ForeignKey(
                help_text="Пользователь, который создал и отправляет заявку в системе.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправитель",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Все авторы материала. Отправитель добавляется автоматически.",
                related_name="authored_submissions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Авторы",
            ),
        ),
        migrations.RunPython(populate_submission_authors, migrations.RunPython.noop),
    ]
