server {
    listen 80;
    listen [::]:80;
    server_name 185.221.154.185;

    client_max_body_size 50M;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type text/plain;
    }

    location /static/ {
        alias /opt/webtstu/app/staticfiles/;
        access_log off;
        expires 7d;
    }

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://unix:/run/webtstu/gunicorn.sock;
        proxy_connect_timeout 30s;
        proxy_read_timeout 180s;
        proxy_send_timeout 180s;
    }
}
