# Generated by Django 5.2.15 on 2026-07-03 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_blocking', models.BooleanField(default=True, verbose_name='Блокирующая')),
                ('backend_code', models.CharField(default='mock_basic', max_length=64, verbose_name='Код обработчика')),
            ],
            options={
                'verbose_name': 'Определение проверки',
                'verbose_name_plural': 'Определения проверок',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('passed', 'Пройдена'), ('failed', 'Не пройдена')], default='pending', max_length=16, verbose_name='Статус')),
                ('result_payload', models.JSONField(blank=True, default=dict, verbose_name='Результат')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Запущена')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('check_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='checks.checkdefinition', verbose_name='Проверка')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_runs', to='submissions.submission', verbose_name='Заявка')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_runs', to='submissions.submissionversion', verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'Запуск проверки',
                'verbose_name_plural': 'Запуски проверок',
                'ordering': ('-created_at',),
            },
        ),
    ]
