# Generated by Django 5.2.15 on 2026-09-06 19:35

import apps.template_workspace.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('article', models.FileField(max_length=500, upload_to=apps.template_workspace.models.job_upload)),
                ('template', models.FileField(max_length=500, upload_to=apps.template_workspace.models.job_upload)),
                ('article_name', models.CharField(max_length=255)),
                ('template_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('plan', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
