# Generated by Django 5.2.15 on 2026-07-03 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('directory', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('active', 'Активна'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('revision_requested', 'Возврат на доработку')], default='pending', max_length=32, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Активирована')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Решение принято')),
                ('assigned_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_tasks', to='auth.group', verbose_name='Группа')),
                ('assigned_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_tasks', to='directory.orgunit', verbose_name='Подразделение')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задача согласования',
                'verbose_name_plural': 'Задачи согласования',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RouteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет')),
                ('revision_strategy', models.CharField(choices=[('restart_current_step', 'Повторить текущий этап'), ('restart_route', 'Перезапустить маршрут')], default='restart_current_step', max_length=32, verbose_name='Стратегия доработки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('article_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_templates', to='directory.articletype', verbose_name='Тип статьи')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_templates', to='directory.journal', verbose_name='Журнал')),
            ],
            options={
                'verbose_name': 'Шаблон маршрута',
                'verbose_name_plural': 'Шаблоны маршрутов',
                'ordering': ('-priority', 'name'),
            },
        ),
        migrations.CreateModel(
            name='RouteStepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('name', models.CharField(max_length=255, verbose_name='Название этапа')),
                ('assignee_kind', models.CharField(choices=[('author_unit_group', 'Группа в подразделении автора'), ('fixed_unit_group', 'Группа в указанном подразделении'), ('fixed_user', 'Конкретный пользователь'), ('fixed_group', 'Группа пользователей')], max_length=32, verbose_name='Тип исполнителя')),
                ('can_reject', models.BooleanField(default=True, verbose_name='Можно отклонить')),
                ('can_request_revision', models.BooleanField(default=True, verbose_name='Можно вернуть на доработку')),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_step_templates', to='auth.group', verbose_name='Группа')),
                ('target_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_step_templates', to='directory.orgunit', verbose_name='Подразделение')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_step_templates', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('route_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_templates', to='workflow.routetemplate', verbose_name='Шаблон маршрута')),
            ],
            options={
                'verbose_name': 'Шаг шаблона маршрута',
                'verbose_name_plural': 'Шаги шаблона маршрута',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TaskDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Одобрить'), ('reject', 'Отклонить'), ('request_revision', 'На доработку'), ('comment', 'Комментарий')], max_length=32, verbose_name='Решение')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Кто принял решение')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='workflow.approvaltask', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Решение по задаче',
                'verbose_name_plural': 'Решения по задачам',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('active', 'Активен'), ('paused_for_revision', 'На доработке'), ('completed', 'Завершен'), ('rejected', 'Отклонен')], default='pending', max_length=32, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Запущен')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('route_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_runs', to='workflow.routetemplate', verbose_name='Шаблон маршрута')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='submissions.submission', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Запуск маршрута',
                'verbose_name_plural': 'Запуски маршрутов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок')),
                ('name', models.CharField(max_length=255, verbose_name='Название этапа')),
                ('assignee_kind', models.CharField(choices=[('author_unit_group', 'Группа в подразделении автора'), ('fixed_unit_group', 'Группа в указанном подразделении'), ('fixed_user', 'Конкретный пользователь'), ('fixed_group', 'Группа пользователей')], max_length=32, verbose_name='Тип исполнителя')),
                ('can_reject', models.BooleanField(default=True, verbose_name='Можно отклонить')),
                ('can_request_revision', models.BooleanField(default=True, verbose_name='Можно вернуть на доработку')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('active', 'Активен'), ('approved', 'Одобрен'), ('rejected', 'Отклонен'), ('revision_requested', 'Возврат на доработку'), ('skipped', 'Пропущен')], default='pending', max_length=32, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Запущен')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('assigned_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_steps', to='auth.group', verbose_name='Группа')),
                ('assigned_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_steps', to='directory.orgunit', verbose_name='Подразделение')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_steps', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('step_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_steps', to='workflow.routesteptemplate', verbose_name='Шаблон шага')),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.workflowrun', verbose_name='Запуск маршрута')),
            ],
            options={
                'verbose_name': 'Шаг маршрута',
                'verbose_name_plural': 'Шаги маршрута',
                'ordering': ('workflow_run_id', 'order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowstep', verbose_name='Текущий шаг'),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='workflow_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workflow.workflowstep', verbose_name='Шаг маршрута'),
        ),
        migrations.AddConstraint(
            model_name='routesteptemplate',
            constraint=models.UniqueConstraint(fields=('route_template', 'order'), name='unique_route_step_order'),
        ),
        migrations.AddConstraint(
            model_name='workflowstep',
            constraint=models.UniqueConstraint(fields=('workflow_run', 'order'), name='unique_workflow_step_order'),
        ),
    ]
