# Generated by Django 5.2.15 on 2026-07-05 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('directory', '0002_direction'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routetemplate',
            options={'ordering': ('direction__name', '-priority', 'name'), 'verbose_name': 'Шаблон маршрута', 'verbose_name_plural': 'Шаблоны маршрутов'},
        ),
        migrations.AlterModelOptions(
            name='taskdecision',
            options={'ordering': ('created_at', 'id'), 'verbose_name': 'Результат этапа', 'verbose_name_plural': 'Результаты этапов'},
        ),
        migrations.AddField(
            model_name='routetemplate',
            name='direction',
            field=models.ForeignKey(blank=True, help_text='Направление определяет, какой маршрут пользователь сможет выбрать при отправке статьи.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_templates', to='directory.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='approvaltask',
            name='assigned_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_tasks', to='auth.group', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='approvaltask',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Результат зафиксирован'),
        ),
        migrations.AlterField(
            model_name='routesteptemplate',
            name='assignee_kind',
            field=models.CharField(choices=[('author_unit_group', 'Роль в подразделении автора'), ('fixed_unit_group', 'Роль в указанном подразделении'), ('fixed_user', 'Конкретный пользователь'), ('fixed_group', 'Общая роль')], max_length=32, verbose_name='Тип исполнителя'),
        ),
        migrations.AlterField(
            model_name='routesteptemplate',
            name='target_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_step_templates', to='auth.group', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='taskdecision',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Кто зафиксировал результат'),
        ),
        migrations.AlterField(
            model_name='taskdecision',
            name='decision',
            field=models.CharField(choices=[('approve', 'Согласовано'), ('reject', 'Отклонено'), ('request_revision', 'На доработку'), ('comment', 'Комментарий')], max_length=32, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='assigned_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_steps', to='auth.group', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='assignee_kind',
            field=models.CharField(choices=[('author_unit_group', 'Роль в подразделении автора'), ('fixed_unit_group', 'Роль в указанном подразделении'), ('fixed_user', 'Конкретный пользователь'), ('fixed_group', 'Общая роль')], max_length=32, verbose_name='Тип исполнителя'),
        ),
    ]
