# Generated by Codex on 2026-07-05

from django.db import migrations


def seed_default_direction(apps, schema_editor):
    Direction = apps.get_model("directory", "Direction")
    Submission = apps.get_model("submissions", "Submission")
    RouteTemplate = apps.get_model("workflow", "RouteTemplate")

    default_direction, _ = Direction.objects.get_or_create(
        code="general",
        defaults={
            "name": "Общее направление",
            "description": "Автоматически создано для существующих заявок и шаблонов маршрутов.",
            "is_active": True,
        },
    )

    Submission.objects.filter(direction__isnull=True).update(direction=default_direction)
    RouteTemplate.objects.filter(direction__isnull=True).update(direction=default_direction)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_submission_direction"),
        ("workflow", "0002_alter_routetemplate_options_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_default_direction, reverse_code=noop_reverse),
    ]
