# Generated by Django 5.1.8 on 2026-07-06 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('directory', '0003_alter_orgunit_options_orgunit_available_roles_and_more'),
        ('workflow', '0004_route_template_direction_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaltask',
            name='assigned_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_tasks', to='directory.orgunit', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='routesteptemplate',
            name='assignee_kind',
            field=models.CharField(choices=[('author_unit_group', 'Роль в группе автора'), ('fixed_unit_group', 'Роль в указанной группе'), ('fixed_user', 'Конкретный пользователь'), ('fixed_group', 'Общая роль')], help_text='Выберите, как назначается этап: по роли автора в его группе, по роли конкретной группы, на конкретного пользователя или на общую роль.', max_length=32, verbose_name='Тип исполнителя'),
        ),
        migrations.AlterField(
            model_name='routesteptemplate',
            name='target_group',
            field=models.ForeignKey(blank=True, help_text='Заполняется для вариантов с ролью: "Роль в группе автора", "Роль в указанной группе" или "Общая роль".', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_step_templates', to='auth.group', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='routesteptemplate',
            name='target_unit',
            field=models.ForeignKey(blank=True, help_text='Заполняется только для варианта "Роль в указанной группе". Для варианта "Роль в группе автора" группа подставится из карточки автора.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_step_templates', to='directory.orgunit', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='assigned_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_steps', to='directory.orgunit', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='assignee_kind',
            field=models.CharField(choices=[('author_unit_group', 'Роль в группе автора'), ('fixed_unit_group', 'Роль в указанной группе'), ('fixed_user', 'Конкретный пользователь'), ('fixed_group', 'Общая роль')], max_length=32, verbose_name='Тип исполнителя'),
        ),
    ]
