# Generated by Django 5.2.15 on 2026-07-06 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_alter_approvaltask_assigned_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='step_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_steps', to='workflow.routesteptemplate', verbose_name='Шаблон шага'),
        ),
    ]
