# Generated by Codex on 2026-07-09

from django.db import migrations, models


def _assignment_key(step):
    return (
        step.target_unit_id,
        step.target_group_id,
        step.target_user_id,
    )


def collapse_route_templates(apps, schema_editor):
    RouteTemplate = apps.get_model("workflow", "RouteTemplate")
    RouteStepTemplate = apps.get_model("workflow", "RouteStepTemplate")
    RouteStepDirectionAssignment = apps.get_model("workflow", "RouteStepDirectionAssignment")
    ArticleType = apps.get_model("directory", "ArticleType")
    Submission = apps.get_model("submissions", "Submission")
    WorkflowRun = apps.get_model("workflow", "WorkflowRun")

    for article_type in ArticleType.objects.all().order_by("id"):
        article_templates = list(
            RouteTemplate.objects.filter(article_type_id=article_type.id).order_by("priority", "id")
        )
        if not article_templates:
            continue

        base_template = (
            RouteTemplate.objects.filter(
                article_type_id=article_type.id,
                direction__isnull=True,
            )
            .order_by("id")
            .first()
        )
        legacy_templates = [template for template in article_templates if template.direction_id is not None]
        representative_template = legacy_templates[0] if legacy_templates else article_templates[0]

        if base_template is None:
            base_template = RouteTemplate.objects.create(
                name=f"Базовый маршрут: {article_type.name}",
                article_type_id=article_type.id,
                direction_id=None,
                priority=representative_template.priority,
                revision_strategy=representative_template.revision_strategy,
                is_active=True,
            )
        else:
            updated_fields = []
            expected_name = f"Базовый маршрут: {article_type.name}"
            if base_template.name != expected_name:
                base_template.name = expected_name
                updated_fields.append("name")
            if not base_template.is_active:
                base_template.is_active = True
                updated_fields.append("is_active")
            if updated_fields:
                base_template.save(update_fields=updated_fields)

        steps_by_order = {}
        for step in RouteStepTemplate.objects.filter(route_template_id=representative_template.id).order_by("order", "id"):
            steps_by_order.setdefault(step.order, {"sample": step, "items": []})

        for template in legacy_templates:
            for step in RouteStepTemplate.objects.filter(route_template_id=template.id).order_by("order", "id"):
                steps_by_order.setdefault(step.order, {"sample": step, "items": []})
                steps_by_order[step.order]["items"].append(step)

        for order in sorted(steps_by_order):
            sample = steps_by_order[order]["sample"]
            items = steps_by_order[order]["items"] or [sample]
            assignment_variants = {_assignment_key(step) for step in items}
            use_direction_rules_only = len(assignment_variants) > 1

            base_step, created = RouteStepTemplate.objects.get_or_create(
                route_template_id=base_template.id,
                order=order,
                defaults={
                    "name": sample.name,
                    "assignee_kind": sample.assignee_kind,
                    "target_group_id": None if use_direction_rules_only else sample.target_group_id,
                    "target_unit_id": None if use_direction_rules_only else sample.target_unit_id,
                    "target_user_id": None if use_direction_rules_only else sample.target_user_id,
                    "can_reject": sample.can_reject,
                    "can_request_revision": sample.can_request_revision,
                },
            )

            if not created:
                base_step.name = sample.name
                base_step.assignee_kind = sample.assignee_kind
                base_step.can_reject = sample.can_reject
                base_step.can_request_revision = sample.can_request_revision
                if use_direction_rules_only:
                    base_step.target_group_id = None
                    base_step.target_unit_id = None
                    base_step.target_user_id = None
                else:
                    base_step.target_group_id = sample.target_group_id
                    base_step.target_unit_id = sample.target_unit_id
                    base_step.target_user_id = sample.target_user_id
                base_step.save(
                    update_fields=[
                        "name",
                        "assignee_kind",
                        "target_group",
                        "target_unit",
                        "target_user",
                        "can_reject",
                        "can_request_revision",
                    ]
                )

            if use_direction_rules_only:
                for step in items:
                    if step.route_template.direction_id is None:
                        continue
                    RouteStepDirectionAssignment.objects.update_or_create(
                        step_template_id=base_step.id,
                        direction_id=step.route_template.direction_id,
                        defaults={
                            "target_group_id": step.target_group_id,
                            "target_unit_id": step.target_unit_id,
                            "target_user_id": step.target_user_id,
                        },
                    )

        for legacy_template in legacy_templates:
            Submission.objects.filter(route_template_id=legacy_template.id).update(route_template_id=base_template.id)
            WorkflowRun.objects.filter(route_template_id=legacy_template.id).update(route_template_id=base_template.id)

        RouteTemplate.objects.filter(
            article_type_id=article_type.id,
            direction__isnull=False,
        ).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0007_routetemplate_article_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routetemplate",
            name="direction",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Для новых базовых маршрутов поле не заполняется: область влияет только на состав исполнителей "
                    "внутри шагов. Поле оставлено для истории и совместимости со старыми маршрутами."
                ),
                null=True,
                on_delete=models.deletion.PROTECT,
                related_name="route_templates",
                to="directory.direction",
                verbose_name="Область экспертизы",
            ),
        ),
        migrations.AddConstraint(
            model_name="routetemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    article_type__isnull=False,
                    direction__isnull=True,
                ),
                fields=("article_type",),
                name="unique_base_route_template_per_article_type",
            ),
        ),
        migrations.CreateModel(
            name="RouteStepDirectionAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="route_step_assignments",
                        to="directory.direction",
                        verbose_name="Область экспертизы",
                    ),
                ),
                (
                    "target_group",
                    models.ForeignKey(
                        on_delete=models.deletion.PROTECT,
                        related_name="route_step_direction_assignments",
                        to="auth.group",
                        verbose_name="Роль",
                    ),
                ),
                (
                    "target_unit",
                    models.ForeignKey(
                        on_delete=models.deletion.PROTECT,
                        related_name="route_step_direction_assignments",
                        to="directory.orgunit",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Необязательно. Если не указан, задача будет назначена на роль и группу.",
                        null=True,
                        on_delete=models.deletion.PROTECT,
                        related_name="route_step_direction_assignments",
                        to="accounts.user",
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "step_template",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="direction_assignments",
                        to="workflow.routesteptemplate",
                        verbose_name="Шаг шаблона",
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение шага по области",
                "verbose_name_plural": "Назначения шагов по областям",
                "ordering": ("step_template_id", "direction__name", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="routestepdirectionassignment",
            constraint=models.UniqueConstraint(
                fields=("step_template", "direction"),
                name="unique_route_step_direction_assignment",
            ),
        ),
        migrations.RunPython(collapse_route_templates, migrations.RunPython.noop),
    ]
