# Generated by Django 5.2.15 on 2026-07-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_base_route_templates_and_direction_assignments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routetemplate',
            options={'ordering': ('direction__name', 'article_type__name', '-priority', 'name'), 'verbose_name': 'Шаблон маршрута', 'verbose_name_plural': 'Шаблоны маршрутов'},
        ),
        migrations.AlterField(
            model_name='routetemplate',
            name='name',
            field=models.CharField(help_text='Например: базовый маршрут для материала или маршрут с дополнительной проверкой.', max_length=255, verbose_name='Название'),
        ),
    ]
