# Generated by Codex on 2026-07-09

from django.db import migrations


def delete_legacy_route_templates(apps, schema_editor):
    RouteTemplate = apps.get_model("workflow", "RouteTemplate")
    RouteStepTemplate = apps.get_model("workflow", "RouteStepTemplate")
    WorkflowStep = apps.get_model("workflow", "WorkflowStep")

    legacy_templates = RouteTemplate.objects.filter(direction__isnull=False)
    if not legacy_templates.exists():
        return

    legacy_template_ids = list(legacy_templates.values_list("id", flat=True))
    legacy_steps = WorkflowStep.objects.filter(step_template__route_template_id__in=legacy_template_ids)

    for workflow_step in legacy_steps.select_related("workflow_run__route_template", "step_template__route_template"):
        base_template = workflow_step.workflow_run.route_template
        if base_template is None:
            base_template = RouteTemplate.objects.filter(
                article_type_id=workflow_step.step_template.route_template.article_type_id,
                direction__isnull=True,
            ).first()

        base_step = None
        if base_template is not None:
            base_step = RouteStepTemplate.objects.filter(
                route_template_id=base_template.id,
                order=workflow_step.order,
            ).first()

        workflow_step.step_template_id = base_step.id if base_step is not None else None
        workflow_step.save(update_fields=["step_template"])

    RouteTemplate.objects.filter(id__in=legacy_template_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0009_alter_routetemplate_options_alter_routetemplate_name"),
    ]

    operations = [
        migrations.RunPython(delete_legacy_route_templates, migrations.RunPython.noop),
    ]
