# Generated by Django 5.1.8 on 2026-07-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_delete_legacy_route_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routesteptemplate',
            name='assignee_kind',
            field=models.CharField(choices=[('author_unit_group', 'Роль в группе автора'), ('author_chair_head', 'Заведующий кафедрой автора'), ('fixed_unit_group', 'Роль в указанной группе'), ('fixed_user', 'Конкретный пользователь'), ('fixed_group', 'Общая роль')], help_text='Выберите, как назначается этап: по заведующему кафедрой автора или по роли конкретной группы.', max_length=32, verbose_name='Тип исполнителя'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='assignee_kind',
            field=models.CharField(choices=[('author_unit_group', 'Роль в группе автора'), ('author_chair_head', 'Заведующий кафедрой автора'), ('fixed_unit_group', 'Роль в указанной группе'), ('fixed_user', 'Конкретный пользователь'), ('fixed_group', 'Общая роль')], max_length=32, verbose_name='Тип исполнителя'),
        ),
    ]
