# Generated by Django 5.2.15 on 2026-07-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_alter_routesteptemplate_assignee_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='awaiting_route_approval',
            field=models.BooleanField(default=False, verbose_name='Ожидает проверки маршрута кафедрой'),
        ),
    ]
