# Generated by Django 5.1.8 on 2026-07-06 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('directory', '0002_direction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgunit',
            options={'ordering': ('name',), 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AddField(
            model_name='orgunit',
            name='available_roles',
            field=models.ManyToManyField(blank=True, help_text='Выберите роли, которые могут существовать внутри этой группы.', related_name='org_units', to='auth.group', verbose_name='Роли группы'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='directory.orgunit', verbose_name='Родительская группа'),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='type',
            field=models.CharField(choices=[('department', 'Кафедра'), ('office', 'Отдел'), ('committee', 'Комиссия')], default='department', max_length=32, verbose_name='Тип группы'),
        ),
    ]
