# Generated by Django 5.2.15 on 2026-07-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_populate_available_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='articletype',
            options={'ordering': ('name',), 'verbose_name': 'Тип материала', 'verbose_name_plural': 'Типы материалов'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ('name',), 'verbose_name': 'Область экспертизы', 'verbose_name_plural': 'Области экспертизы'},
        ),
    ]
