# Generated by Django 5.2.15 on 2026-07-13 12:04

import apps.conclusions.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0007_submission_authors'),
        ('workflow', '0012_workflowrun_awaiting_route_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConclusionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=64, unique=True, verbose_name='Регистрационный номер')),
                ('source_docx_file', models.FileField(upload_to=apps.conclusions.models.conclusion_docx_upload_to, verbose_name='Исходное заключение DOCX')),
                ('pdf_file', models.FileField(upload_to=apps.conclusions.models.conclusion_pdf_upload_to, verbose_name='Неизменяемое заключение PDF')),
                ('document_sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256 PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Сформировано')),
                ('sealed_at', models.DateTimeField(blank=True, null=True, verbose_name='Зафиксировано')),
                ('is_sealed', models.BooleanField(default=False, editable=False)),
                ('source_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conclusion_documents', to='submissions.submissionversion', verbose_name='Версия рукописи при формировании')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conclusion_documents', to='submissions.submission', verbose_name='Заявка')),
                ('workflow_run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conclusion_document', to='workflow.workflowrun', verbose_name='Запуск маршрута')),
            ],
            options={
                'verbose_name': 'Заключение',
                'verbose_name_plural': 'Заключения',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ConclusionSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=255, verbose_name='ФИО подписанта')),
                ('signer_role', models.CharField(max_length=255, verbose_name='Роль подписанта')),
                ('submission_version_number', models.PositiveIntegerField(verbose_name='Номер одобренной версии')),
                ('submission_version_sha256', models.CharField(max_length=64, verbose_name='SHA-256 одобренной версии')),
                ('document_sha256', models.CharField(max_length=64, verbose_name='SHA-256 подписанного PDF')),
                ('operation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('confirmation_method', models.CharField(default='authenticated_session', editable=False, max_length=64, verbose_name='Способ подтверждения')),
                ('client_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('user_agent', models.TextField(blank=True, editable=False)),
                ('signed_payload', models.JSONField(editable=False, verbose_name='Зафиксированные данные операции')),
                ('previous_event_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('event_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('signed_at', models.DateTimeField(verbose_name='Подписано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Запись создана')),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conclusion_signature', to='workflow.taskdecision', verbose_name='Решение')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='conclusions.conclusiondocument', verbose_name='Заключение')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conclusion_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Подписант')),
                ('submission_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conclusion_signatures', to='submissions.submissionversion', verbose_name='Одобренная версия рукописи')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='conclusion_signature', to='workflow.approvaltask', verbose_name='Задача согласования')),
            ],
            options={
                'verbose_name': 'Подпись ПЭП заключения',
                'verbose_name_plural': 'Подписи ПЭП заключений',
                'ordering': ('signed_at', 'id'),
            },
        ),
    ]
