# Generated by Django 5.2.15 on 2026-07-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_planningrosterentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='activity',
            name='source_cell',
            field=models.CharField(blank=True, max_length=16, verbose_name='Ячейка-источник'),
        ),
        migrations.AddField(
            model_name='activity',
            name='source_file',
            field=models.CharField(blank=True, max_length=500, verbose_name='Файл-источник'),
        ),
        migrations.AddField(
            model_name='activity',
            name='source_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='Ключ импорта'),
        ),
        migrations.AddField(
            model_name='activity',
            name='source_sheet',
            field=models.CharField(blank=True, max_length=64, verbose_name='Лист-источник'),
        ),
        migrations.AddField(
            model_name='activity',
            name='source_text',
            field=models.TextField(blank=True, verbose_name='Исходная формулировка'),
        ),
    ]
